<?php

namespace SenseiTarzan\OldSystemMove;

use pocketmine\plugin\PluginBase;
use pocketmine\utils\SingletonTrait;
use SenseiTarzan\OldSystemMove\Listener\PacketListener;
use SenseiTarzan\ExtraEvent\Component\EventLoader;

class Main extends PluginBase
{
    use SingletonTrait;
    protected function onLoad(): void
    {
        self::setInstance($this);
        parent::onLoad(); // TODO: Change the autogenerated stub
    }

    protected function onEnable(): void
    {
        EventLoader::loadEventWithClass($this, PacketListener::class);

    }
}